mod client;
mod config;
mod date;
mod error;
mod http_client;
mod ids;
mod types;

pub use client::Client;
pub use types::Boxscore;
pub use types::ClubStats;
pub use types::TeamGameStats;
pub use types::Conference;
pub use types::DailySchedule;
pub use types::Division;
pub use types::GameClock;
pub use types::AssistSummary;
pub use types::GameMatchup;
pub use types::GameSummary;
pub use types::GoalSummary;
pub use types::GoalieStats;
pub use types::LocalizedString;
pub use types::PeriodDescriptor;
pub use types::PeriodScoring;
pub use types::PlayByPlay;
pub use types::PlayerGameLog;
pub use types::PlayerLanding;
pub use types::PlayerSearchResult;
pub use types::ScheduleGame;
pub use types::ScheduleTeam;
pub use types::SkaterStats;
pub use types::Standing;
pub use types::TeamPlayerStats;
//pub use types::Team;
pub use config::ClientConfig;
pub use date::GameDate;
pub use error::NHLApiError;
pub use ids::GameId;
pub use types::GameState;
