//! Shared enums for NHL API types
//!
//! This module re-exports all enum types from their logical groupings:
//! - `player_enums`: Player-related enums (Position, Handedness, GoalieDecision)
//! - `game_enums`: Game/play-related enums (PeriodType, HomeRoad, ZoneCode, DefendingSide, GameScheduleState)
//!
//! String-backed enums are generated by the [`nhl_string_enum!`] macro (see
//! `macros.rs`), which gives every enum a uniform code/name/Display/FromStr/serde
//! surface and routes unknown values through the shared [`UnknownEnumValue`] error.

use thiserror::Error;

pub(crate) mod macros;

mod game_enums;
mod player_enums;

pub use game_enums::*;
pub use player_enums::*;

/// Error returned when a value received from the API does not match any known
/// variant of a strongly-typed string enum.
///
/// It is returned by every macro-generated `FromStr` implementation. Because
/// enum deserialization failures propagate up and fail the whole response decode,
/// callers can match on this error to recover exactly which enum type and raw
/// value were unrecognized — for example, to log a value the NHL API newly
/// introduced before this library was updated to recognize it.
///
/// # serde limitation
///
/// serde's error trait cannot carry a typed payload, so the macro-generated
/// `Deserialize` implementations surface this error through
/// [`serde::de::Error::custom`]. The resulting `serde_json::Error` preserves the
/// diagnostic message (`invalid <enum_name>: "<value>"`, matching the Go client)
/// but not the recoverable typed error; use `FromStr` directly when you need to
/// pattern-match on [`UnknownEnumValue`].
#[derive(Error, Debug, Clone, PartialEq, Eq)]
#[error("invalid {enum_name}: {value:?}")]
pub struct UnknownEnumValue {
    /// Human-readable label for the enum, e.g. `"period type"`.
    pub enum_name: &'static str,
    /// The unrecognized raw value as received from the API.
    pub value: String,
}
